### ISSUE TITLE
Hello! 

### ISSUE THREAD

**Issue by aloneuser** [MioVisman/FluxBB_by_Visman#2]
Здравствуйте!
Что случилось с сайтом fluxbb.org.ru ?
Если хотите, я могу заняться его поддержкой - оплата хостинга и домена будет за мной.

**Comment by MioVisman** [comment]
Привет!
Я не являюсь владельцем этого сайта.
Сейчас сайт находится по адресу fluxbb.qb7.ru

**Comment by aloneuser** [comment]
Это не может не радовать.
Visman пишет:
