### ISSUE TITLE
Problems enabling secure SMTP

### ISSUE THREAD

**Issue by ThatRoboticFish** [MioVisman/FluxBB_by_Visman#29]
I have a FluxBB Visman forum running at bbs.igloocafe.space (running the latest release, not the git version). I have been trying for a long time to enable my email server (Postfix with TLS) on my forum but when I enable the SSL option, any user that registers or wants to request a password reset with their email address gets this error:

``
PHP message: PHP Warning:  fsockopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number in /var/www/X/include/email.php on line 336PHP message: PHP Warning:  fsockopen(): Failed to enable crypto in /var/www/X/include/email.php on line 336PHP message: PHP Warning:  fsockopen(): unable to connect to ssl://igloocafe.space:25 (Unknown error) in /var/www/X/include/email.php on line 336" while reading response header from upstream
``

 and if I don't enable it, it simply returns a "Relay access error". Why is there no option to enable TLS on this forum software?

**Comment by MioVisman** [comment]
>Why is there no option to enable TLS on this forum software?

Because until today, no one has changed the function of sending mail via the smtp server since punbb 1.2.


Added TLS support similar to ForkBB. But it needs to be tested.
Option "Encrypt SMTP using SSL" = NO for TLS.

**Comment by ThatRoboticFish** [comment]
Closing this, I managed to fix this issue using these options.
![imagen](https://github.com/MioVisman/FluxBB_by_Visman/assets/113400974/7021a0cb-ccbd-4563-b0ce-d7ec524de514)
The options are really confusing and that is why they have led me to make this problem, sorry for the inconvenience.
