### ISSUE TITLE
“Bad csrf_hash” when previewing/posting if a forum is running under Cloudflare

### ISSUE THREAD

**Issue by ThatRoboticFish** [MioVisman/FluxBB_by_Visman#39]
I'm now running my forum under a Cloudflare reverse proxy due to security reasons. One problem I have is that when I want to edit/create a post and preview the changes, I get a “Bad csrf_hash. You were referred to this page from an unauthorized source." error. What is causing this? I don't think this is a issue directly from the forum but from the proxy.

![imagen](https://github.com/MioVisman/FluxBB_by_Visman/assets/113400974/a9f6daf2-3f82-41ad-b205-698622a6928d)

**Comment by ThatRoboticFish** [comment]
Welp, seems like I managed to fix this by just adding the Cloudflare IPs on the Nginx block

```
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 104.16.0.0/12;
set_real_ip_from 104.24.0.0/12;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 199.27.128.0/21;

set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2a06:98c0::/29;
set_real_ip_from 2c0f:f248::/32;

real_ip_header CF-Connecting-IP;
```

**Comment by MioVisman** [comment]
Log your ip when opening a message form, when previewing and when saving. Perhaps they are different?

**Comment by ThatRoboticFish** [comment]
> Log your ip when opening a message form, when previewing and when saving. Perhaps they are different?

Yes, it is.

![imagen](https://github.com/MioVisman/FluxBB_by_Visman/assets/113400974/7f67374e-354e-44aa-be10-3efe56d47b38)
![imagen](https://github.com/MioVisman/FluxBB_by_Visman/assets/113400974/cc0f92ed-ad5c-44b6-9438-693371c65740)
