### ISSUE TITLE
Request to Add Link to Language Translation in README.md

### ISSUE THREAD

**Issue by tanziran** [MioVisman/FluxBB_by_Visman#42]
Hello
I hope this message is helpful to you. I am a follower of your project FluxBB_by_Visman and have recently contributed Chinese translations to the project. Translations are hosted at [github](https://github.com/tanziran/langs). Hopefully, you can add a link to the language library in your project's README. I also hope that more people will see this library and contribute to fluxbb. There may be a problem with the translation, I don't understand English, so there may be some language issues and distortions in the issues, please forgive me.

**Comment by tanziran** [comment]
The Chinese Simplified Chinese translation of the language library should not be too much of a problem, because I still have the function to translate it according to Google Translate

**Comment by MioVisman** [comment]
Thank you!
https://github.com/MioVisman/FluxBB_by_Visman/commit/995fda047ef035383b8cb08262535717d18fdca4
