### ISSUE TITLE
What should I do if I want to migrate an online FluxBB to use this version?

### ISSUE THREAD

**Issue by qijianjun** [MioVisman/FluxBB_by_Visman#7]
Hello, I have a forum runs on the official version with a few mods, and I want to migrate to this version, is it OK if I just make the apache server to use a new path as website directory?

**Comment by MioVisman** [comment]
**First of all make a backup database and forum catalog.**

Try to do an upgrade on a copy of the database and forum directory.

The config.php file should be in the include/ directory and looks like this:

```
<?php

$db_type = ...;
$db_host = ...;
$db_name = ...;
$db_username = ...;
$db_password = ...;
$db_prefix = ...;
$p_connect = ...;

$cookie_name = ...;
$cookie_domain = ...;
$cookie_path = ...;
$cookie_secure = ...;
$cookie_seed = ...;

$salt1 = '';

define('PUN', 1);

//define('PUN_DEBUG', 1);
//define('PUN_SHOW_QUERIES', 1);
define('PUN_MAX_POSTSIZE', 65535);
//define('FORUM_EOL', "\r\n"); // possible values can be PHP_EOL, "\r\n", "\n" or "\r"
//define('FORUM_UA_OFF', 1);
define('FORUM_AJAX_JQUERY', '//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js');
```

**Comment by qijianjun** [comment]
I follow your instruction but encountered with db error, I check the debug info and found there are two tables(online & forum) altered with additional columns.

I made changes to the two tables and build the 8 new tables(pms_new_block / pms_new_posts / pms_new_topics / poll / poll_voted / sec_of_login / smilies / warnings), and the website lead me to the db_upgrade.php page. I have upgraded the website and it works well, thanks!

**Comment by MioVisman** [comment]
Hmm, the db_update.php file had to start automatically and change the structure of the database -> https://github.com/MioVisman/FluxBB_by_Visman/blob/master/db_update.php#L1827-L2433
