### ISSUE TITLE
video links auto spoiler

### ISSUE THREAD

**Issue by SOTVM** [MioVisman/FluxBB_by_Visman#8]
how to make links to video automatically hiding under the spoiler ?
`[spoiler=video]https://www.youtube.com/watch?v=U475MNNjLN0[/spoiler]`

**Comment by MioVisman** [comment]
Maybe the best solution is lazyload?
The images hidden in the spoiler are loaded before it is opened, the video, I think, will also be downloaded immediately.

P.S. Можно на русском общаться.

**Comment by SOTVM** [comment]
по русски? да не вопрос,что сразу видно что русский?
я думал вы какой то а-ля испанец :)
есть форум http://zenway.ru/forum/ (не мой )
в ветке а по3,14здеть много видео,страница подвисает.
я предложил сократить вывод постов на страницу,
а потом подумал что их все можно под  спойлер
(опцию поставить в настройках).
я думаю это полезно и не очень сложно,
сам глянул js (уже не вспомню какой),вам видней = вы творец.(по моему media***)
PS
забыл что хотел спросить (я бухой
вспомню напишу
ваш форум лучший (я перепробовал "много")

Спасибо что уделили внимание.

**Comment by SOTVM** [comment]
если есть в этом смысл,
я не сильно разбираюсь  в web 
я вообще "пенсионер" ,которому интересно.
я же не всякую ерунду предлагаю.
отложенная загрузка с youtube (я правильно понял? 
объясни как могу=
если на странице много видео ,то страдают те,у кого слабые машины и и-нет
я  один раз попадал на страничку на https://habr.com/ru/
там какойто умник ,в одно сообщение выложил ≈ ± 100 видосов.
а у меня linux + 2gb Ram+2gb Swap
при открытии этого поста система зависала :)
я долго ломал голову,но потом автор статьи сказал:
а хуле ,у меня 16gb и процессор Core i7,
конечно у него всё будет летать,
а у меня сейчас  Athlon x2 5200+  ,которому уже больше 10 лет
:) :) :)

**Comment by SOTVM** [comment]
зы
я вспомнил,о чём хотел сказать!!!
в подсветке синтаксиса ,нет Bash|Sh ,
поэтому отключили ваш плагин highlight
лень писать - я бухой (ссылку дать не могу ,потому так
****************
т.е. сделать подсветку синтаксиса в блоках с кодом - это не сложно (5-10мин.)
с оф.сайта качаешь архив https://highlightjs.org/download/
сначала выдели только нужные языки .
у  себя я оставил только
Bash CSS HTML, XML HTTP JSON JavaScript PHP Python SQL
рапаковываешь архив и кидаешь куда душе угодно. (потом в ссылках только пути поправь)
я просто корне форума создал каталог /forum/highlight/ и всё что было в архиве скинул туда.
потом в главном файле шаблона форума /forum/include/template/main.tpl
перед тэгом закрытия </head> вставляешь 3-ри строчки ссылки на файлы .css и .js + скрипт инициализации.
посмотреть какой выбрать стиль можно там же  на сайте https://highlightjs.org/
я себе поставил railscasts ,соответственно указал его и в ссылке (вместо default.css )

<link rel="stylesheet" href="/forum/highlight/styles/railscasts.css">
<script src="/forum/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

</head>
********************

**Comment by MioVisman** [comment]
Подсветки синтаксиса вообще не было. Это дело админы добавляют у себя на форумы по своему желанию. 
Мне кажется highlightjs_org кривенько работает. Сейчас не посмотришь, но на fluxbb.qb7.ru стоит подсветка и кажется эта. Если строки кода длинные и не помещаются на всю длину, то фон за пределами видимой части при прокрутке по горизонтали отображается другим цветом.

С видео постараюсь поэкспериментировать в это воскресение. Попробую приделать lazyload, чтобы загружались только те видео, которые отображаются на экране.
Против спойлера я против, так как под ним контент все равно грузится и для автоматического добавления bb-кода нужно городить огород в парсере на стороне сервера, а я выносил это все от туда в js на сторону клиента.

**Comment by SOTVM** [comment]
у меня работает красиво
в основном пользуем башеподобные
linuxforum ,другие языки ,как бы и не очень нужны.
что на счёт того ,чтобы добавить опцию в админку (скрыть видео под спойлер)?

**Comment by SOTVM** [comment]
..."Против спойлера я против, так как под ним контент все равно грузится"...
как сделать что не грузил сразу всё,а только превью?
или проще урезать страницу с 50 до 15-20 постов? 
но в пост умудряются и по 10 видосов засунуть 
или банить таких :) без предупреждений :)

**Comment by MioVisman** [comment]
Добавил ленивую загрузку для содержимого фреймов.
Выложил пока на https://fluxbb.org/resources/mods/mediajs/
Можно от туда файл media.min.js скопировать к себе и тестировать на разных браузерах.
У себя протестировал в Firefox и IE11.

**Comment by MioVisman** [comment]
https://caniuse.com/#feat=intersectionobserver
там где браузер зеленый должна работать lazyload.

**Comment by SOTVM** [comment]
у меня
60.7.0esr (64-бит)

**Comment by vovansrnd** [comment]
Всё, спасибо, залил скрипт, вроде бы всё ок!

**Comment by MioVisman** [comment]
Там же выложил обновленную версию.
* ленивая загрузка поддерживает не только фреймы, но и все остальное
* youtube - черный экран превью исправлен
* soundcloud - оставлена поддержка только ссылок вида _api.soundcloud.com/(tracks|playlists)/ID (сервис перестал поддерживать ссылки на страницу с песней во встраиваемом коде)

**Comment by vovansrnd** [comment]
Обновил, спасибо!
