### ISSUE TITLE
Merge checkbox visible when merge plugin disable

### ISSUE THREAD

**Issue by iznogoud59** [MioVisman/FluxBB_by_Visman#9]
Because the checkbox is visible when merge plugin is disable, i've changed :

in post.php, line 749
`if ($is_admmod && !$fid)`
by 
`if ($is_admmod && !$fid && isset($pun_config['o_merge_timeout']) && $pun_config['o_merge_timeout']>0) `

in viewtopic.phop, line 714
`if ($is_admmod)`
by
`if ($is_admmod && isset($pun_config['o_merge_timeout']) && $pun_config['o_merge_timeout']>0)`

Best regard

**Comment by iznogoud59** [comment]
#10 #11

**Comment by MioVisman** [comment]
Thank you!
